---
title: "Untitled"
format: html
---


```{python}
import decoupler as dc
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
```

```{python}
cars = sc.read_h5ad("2.5_car_no_gd.h5ad")
```

# adding a new timepoint category, that splits the late timepoint into late and very late
```{python}
late_dict = {
    "M0":"Product",
    "M01":"Early",
    "M02":"Early",
    "M03":"Early",
    "M04":"Mid",
    "M05":"Mid",
    "M06":"Mid",
    "M09":"Late",
    "M12":"Late",
    "M14":"Late",
    "M15":"Late",
    "M18":"Late",
    "M21":"Late",
    "M30":"VeryLate",
    "M36":"VeryLate",
    "M48":"VeryLate",
    "M60":"VeryLate"
}

cars.obs["timepoint_bin_v2"] = (
    cars.obs["Timepoint"]
    .map(late_dict)
    .astype("category")
)
sc.tl.dendrogram(cars, groupby="timepoint_bin_v2")
```

# also adding pseudotime data generated in slingshot script
```{python}
pt = pd.read_csv("slingshot_pseudotime.csv", index_col="cell")
weights = pd.read_csv("slingshot_lineage_weights.csv", index_col="cell")
weights = weights[["Lineage1", "Lineage3"]]
```

```{python}
pt = pt.loc[cars.obs_names]
weights = weights.loc[cars.obs_names]
```

```{python}
cars.obs["Lineage1_weight"] = weights["Lineage1"]
cars.obs["Lineage3_weight"] = weights["Lineage3"]
```

```{python}
plt.close()
fig=sc.pl.umap(cars, color = ["Lineage1_weight", "Lineage3_weight"], return_fig=True, 
cmap="rocket_r", frameon=False)
fig.set_size_inches(8, 4)
print(fig.get_size_inches())
fig.savefig("car_only/lineage_weights_umap.png", dpi=300, bbox_inches="tight")
plt.close
```

# classifying cells into lineages or branching cells based on their weights
# cells with weigth > 0.8 in lineage 1 and < 0.8 in lineage 2 = lin1 (and vice versa)
# brach cells = those with 0.8 in both, but then excluding earlier clusters to make sure im only capturing the immediate branching point

```{python}
threshold = 0.8

cars.obs["Lineage1_member"] = (cars.obs["Lineage1_weight"] > threshold) & (cars.obs["Lineage3_weight"] < 0.2)
cars.obs["Lineage3_member"] = (cars.obs["Lineage1_weight"] < 0.2) & (cars.obs["Lineage3_weight"] > threshold)
cars.obs["Branch_member"] = (cars.obs["Lineage1_weight"] > threshold) & (cars.obs["Lineage3_weight"] > threshold)
```

```{python}
sc.pl.umap(cars, color = ["Lineage1_member", "Lineage3_member", "Branch_member"])
```

```{python}
cars.obs["lineage_group"] = np.select(
    [
        cars.obs["Lineage1_member"],
        cars.obs["Lineage3_member"],
        cars.obs["Branch_member"],
    ],
    [
        "Lineage1",
        "Lineage3",
        "Branch",
    ],
    default="Other"
)

cars.obs["lineage_group"] = cars.obs["lineage_group"].astype("category")
```

```{python}
plt.close()
fig=sc.pl.umap(cars, color = "lineage_group",return_fig=True, frameon=False)
fig.set_size_inches(4, 4)
print(fig.get_size_inches())
fig.savefig("car_only/umap_lineage_groups.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
cell_counts = cars.obs["lineage_group"].value_counts().reset_index(name="n_cells")

plt.close("all")
plt.figure(figsize=(8,5))

ax=sns.lineplot(
    data=cell_counts,
    x="lineage_group",
    y="n_cells",
    hue="lineage_group",
    marker="o"
)

ax.axvline(
    x=7,              # month where you want the line
    linestyle="--",
    color="black",
    linewidth=1
)

plt.show()
plt.savefig("/car_only/lineage_group_numbers.png", dpi=300, bbox_inches="tight")
plt.close()
```

# finally, i need to allocate cells in the branch lineage that are too early to be truly considered the brnaching point (e.g product cells) into the other group
```{python}
early_clusters = [
    "Product Mixed T",
    "Product CD8+ T",
    "Naive/CM T",
    "Cycling T"
]

cars.obs.loc[
    (cars.obs["lineage_group"] == "Branch") &
    (cars.obs["labels"].isin(early_clusters)),
    "lineage_group"
] = "Other"
```

# adding a new meta column (might not use it) that combined lineage with timepoint
```{python}
cars.obs["lineage_time"] = (
    cars.obs["lineage_group"].astype(str) + "_" + cars.obs["Timepoint_bin"].astype(str)
)
```

```{python}
plt.close()
sc.pl.dotplot(cars, var_names = ["FOXO1", "RASA2", "MED12", "LTBR", "JUN"], groupby = "Timepoint_bin")
plt.close()
```

# running pseudobulk DEA on lineages
```{python}
pdata = dc.pp.pseudobulk(
    adata=cars,
    sample_col="Patient",
    groups_col="lineage_group",
    mode="sum",
    layer="counts"
)
```

```{python}
dc.pl.filter_samples(
    adata=pdata,
    groupby=["Patient", "lineage_group"],
    min_cells=10,
    min_counts=1000,
    figsize=(5, 8),
)
```

```{python}
dc.pp.filter_samples(pdata, min_cells=10, min_counts=1000)
```

```{python}
# Import DESeq2
import pydeseq2
from pydeseq2.dds import DeseqDataSet, DefaultInference
from pydeseq2.ds import DeseqStats

# Build DESeq2 object
inference = DefaultInference(n_cpus=8)
dds = DeseqDataSet(
    adata=pdata,
    design="~lineage_group",
    refit_cooks=True,
    inference=inference,
)

# Compute LFCs
dds.deseq2()

# Extract contrast between conditions
stat_res = DeseqStats(dds, contrast=[""], inference=inference)

# Compute Wald test
stat_res.summary()
```

```{python}
results_df = stat_res.results_df
results_df
```

```{python}
plt.close()

sc.pl.dotplot(
    cars,
    var_names=["ZBTB4", "ZBED1", "MYC", "PTF1A", "SIX4", "GBX2", "MSX1", "RFX1", "HCFC1", "HLF",
    "NFATC1", "SP7", "SMARCA5", "NCOA1", "ZNF148", "DLX4", "DLX2", "BHLHA15", "NEUROD1", "SOX4"],
    groupby="lineage_group",
    standard_scale="var"
)
```


# start TF enrichment analysis
```{python}
collectri = pd.read_csv("../CollecTRI_regulons.csv")
collectri.head()
```

# only include TFs that are not 0 counts in my data
```{python}
X = cars.layers["logcounts"]
expr_fraction = np.asarray((X > 0).mean(axis=0)).flatten()
gene_fraction = dict(zip(cars.var_names, expr_fraction))
expressed_genes = [
    g for g, frac in gene_fraction.items()
    if frac >= 0.01
]
```

```{python}
collectri_filtered = collectri[
    collectri["target"].isin(expressed_genes)
]
collectri_filtered = collectri_filtered[
    collectri_filtered["source"].isin(expressed_genes)
]
```

```{python}
dc.mt.ulm(data=cars, net=collectri_filtered, layer = "logcounts", tmin=10)
```

```{python}
score = dc.pp.get_obsm(adata=cars, key="score_ulm")
score
```

# add a lineage_patient grouping to be able to check if tfs behave the same across individuals
```{python}
score.obs["lineage_patient"] = (
    score.obs["lineage_group"].astype(str) + "_" + cars.obs["Patient"].astype(str)
)
```

```{python}
df = dc.tl.rankby_group(adata=score, groupby="lineage_group", reference="rest", method="t-test_overestim_var")
df = df[df["padj"] < 0.05]
df
```

```{python}
n_markers = 10
source_markers = (
    df.groupby("group")
    .head(n_markers)
    .drop_duplicates("name")
    .groupby("group")["name"]
    .apply(lambda x: list(x))
    .to_dict()
)
source_markers
```

```{python}
plt.close("all")
plt.figure(figsize=(24,8))
sc.pl.matrixplot(
    adata=score,
    var_names=source_markers,
    groupby="lineage_group",
    dendrogram=False,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)
plt.savefig("tf_enrichment/lineage_tfs_heatmap.png", dpi=300)
plt.close()
```

# looking at overlapping TFs between groups

```{python}
df["direction"] = np.where(
    df["stat"] > 0,
    "up",
    "down"
)
```


```{python}
branch = df[df["group"]=="Branch"].set_index("name")
lin1 = df[df["group"]=="Lineage1"].set_index("name")

branch_lin1 = branch.join(
    lin1,
    lsuffix="_branch",
    rsuffix="_lin1"
)

same_direction = branch_lin1[
    branch_lin1["direction_branch"] ==
    branch_lin1["direction_lin1"]
]
```

```{python}
lin3 = df[df["group"]=="Lineage3"].set_index("name")

lin3 = lin3.add_suffix("_lin3")

combined = (
    branch.add_suffix("_branch")
    .join(lin1.add_suffix("_lin1"), how="inner")
    .join(lin3, how="left")
)

persistent_like = combined[
    (
        (combined["direction_branch"]=="up") &
        (combined["direction_lin1"]=="up") &
        (combined["direction_lin3"]!="up")
    )
    |
    (
        (combined["direction_branch"]=="down") &
        (combined["direction_lin1"]=="down") &
        (combined["direction_lin3"]!="down")
    )
]
```

```{python}
persistent_like = persistent_like.sort_values(
    "stat_lin1",
    ascending=False
)
persistent_like = persistent_like.reset_index()
```

```{python}
plt.close("all")
plt.figure(figsize=(24,8))
sc.pl.matrixplot(
    adata=score,
    var_names=persistent_like.name,
    groupby="lineage_group",
    dendrogram=False,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)
plt.savefig("tf_enrichment/persistence_tfs_heatmap.png", dpi=300)
plt.close()
```

```{python}
persistent_up = persistent_like[persistent_like["direction_branch"] == "up"]
persistent_down = persistent_like[persistent_like["direction_branch"] == "down"]
```

```{python}
plt.close("all")
plt.figure(figsize=(10,5))
sc.pl.matrixplot(
    adata=score,
    var_names=persistent_up.name,
    groupby="lineage_group",
    dendrogram=False,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)

plt.savefig("tf_enrichment/persistence_up_tfs_heatmap.png", dpi=300)
plt.close()
```

```{python}
plt.close("all")
plt.figure(figsize=(10,5))
sc.pl.matrixplot(
    adata=score,
    var_names=persistent_down.name,
    groupby="lineage_group",
    dendrogram=False,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)

plt.savefig("tf_enrichment/persistence_down_tfs_heatmap.png", dpi=300)
plt.close()
```

# plotting top enriched and suppressed TFs
```{python}
# top and bottom 10 TFs by branch statistic
plot_base = persistent_like[["name", "stat_branch"]].copy()
top10 = persistent_like.nlargest(10, "stat_branch")
bottom10 = persistent_like.nsmallest(10, "stat_branch")

plot_df = pd.concat([bottom10, top10])
plot_df["name"] = plot_df["name"].astype(str)

plot_df = plot_df.sort_values("stat_branch")


plt.close()
plt.figure()

fig=sns.barplot(
    data=plot_df,
    x="stat_branch",
    y="name",
    hue="stat_branch",
    palette="RdBu_r",
    legend=False
)
fig.figure.set_size_inches(5,3)
plt.xlabel("Branch activity statistic")
plt.ylabel("TF")

plt.savefig(
    "tf_enrichment/persistence_top_bottom_tfs.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close()
```

```{python}
gex_branch= cars[cars.obs["lineage_group"] == "Branch"].to_df().mean(0).to_frame().T
score_branch = score[score.obs["lineage_group"] == "Branch"].to_df().mean(0).to_frame().T

plt.close()
dc.pl.network(
    data=gex_branch,
    score=score_branch,
    net=collectri,
    sources=["NCOA1","SOX4","RORA", "CREBZF"],
    targets=20,
    size_node=5,
    figsize=(5, 5),
    s_cmap="Reds",
    t_cmap="viridis"
)
plt.close()
```

# looking at specific TFs from a recent nature publication to see if they are expressed across celltypes or timepoints
# https://www.nature.com/articles/s41586-025-09989-7
```{python}
markers = {
    "Mem_precurosr": ["HOXB4", "NR6A1", "NFIA", "POU2F2"],
    "Naive": ["MYC","SOX4","TET3","MYNN","EGR3"],
    "TCM": ["CUX1", "NFKB1", "BACH1", "POU5F1"],
    "TEM": ["FOXB1", "FOXF2", "TBX6", "RORB", "CPHXL"],
    "TEX_progenitor": ["NR3C2", "IRF7", "NFKB2", "CEBPD", "STAT5B"],
    "TEX_eff": ["SOX8", "ZNF184", "MXI1", "OVOL2", "RFX4"],
    "TEX_term": ["ZSCAN20", "ZNF143", "ZBTB49", "ZBTB3", "THRB"]
}
```

```{python}
score_no_other = score[score.obs["lineage_group"]!="Other"].copy()
plt.close()
sc.pl.matrixplot(
    adata=score_no_other,
    var_names=plot_df.name,
    groupby="lineage_patient",
    dendrogram=False,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)
```

```{python}
plt.close()
sc.pl.dotplot(
    adata=cars,
    var_names=["GATA3", "STAT6", "IRF4", "STAT5A", "IL4R", "MRPS26", "RORC", "RORA", "KLRB1", "STAT3","TBX21", "IFNG", "IL10", "ITGAE", "CTLA4", "TIGIT", "CD28", "IKZF2", "IL17A", "IL17F", "IL23A", "IL22", "IL4", "IL5", "IL13", "TGFB1", "IL9", "IL21", "STAT1", "STAT4", "TRAF2", "TRAF3", "TRAF6", "CD40", "TNFRSF11A", "LTBR", "SMAD3", "E2F8", "TGFBR1", "TGFBR2", "TGFBR3"],
    groupby="lineage_group",
    dendrogram=True,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)
```

```{python}
plt.close()
sc.pl.dotplot(
    adata=cars,
    var_names=["FOXO1", "JUN", "LTBR"],
    groupby="lineage_group",
    dendrogram=True,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)
```

```{python}
sc.pl.violin(score, keys ="NOTO", groupby="labels",rotation=45)
```

```{python}
gex_branch= cars[cars.obs["lineage_group"] == "Branch"].to_df().mean(0).to_frame().T
score_branch = score[score.obs["lineage_group"] == "Branch"].to_df().mean(0).to_frame().T

dc.pl.network(
    data=gex_branch,
    score=score_branch,
    net=collectri,
    sources=["GATA3", "STAT6", "STAT1"],
    targets=10,
    size_node=5,
    figsize=(5, 5),
    s_cmap="viridis",
    t_cmap="RdBu_r"
)
```

```{python}
late = df[(df["group"] == "Branch")]

top_up = late.nlargest(10, "stat")
top_down = late.nsmallest(10, "stat")

plot_df = pd.concat([top_down, top_up])
plot_df["name"] = plot_df["name"].cat.remove_unused_categories()
plot_df = plot_df.sort_values("stat")
```

```{python}
order = plot_df.sort_values("stat")["name"]
plt.figure(figsize=(8,6))
sns.barplot(plot_df, x = "stat", y = "name", hue = "stat", palette="RdBu_r", order=order)
plt.savefig("tf_enrichment/branch_top_de_tf.png", dpi=300)
plt.close()
```

```{python}
plt.figure(figsize=(10,4))
sc.pl.matrixplot(
    adata=score,
    var_names=plot_df.name,
    groupby="lineage_group",
    dendrogram=True,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r",
)
plt.savefig("tf_enrichment/branch_tfs_heatmap.png", dpi=300)
plt.close()
```

```{python}
gex_late = cars[cars.obs["Timepoint_bin"] == "Late"].to_df().mean(0).to_frame().T
score_late = score[score.obs["Timepoint_bin"] == "Late"].to_df().mean(0).to_frame().T

sources = list(plot_df.name)
source_list = ["MYC", "HOXA2","E2F4","NFYB","NOTO"]

dc.pl.network(
    net=collectri,
    data=gex_late,
    score=score_late,
    sources=source_list,
    targets=10,
    size_node=8,
    size_label=0,
    figsize=(5, 4),
    layout="kk",
    s_cmap="RdPu",
    vcenter=False,
    t_cmap="GnBu",
    s_label="TF activity",
    t_label="log-normalized expression",
    save="tf_enrichment/late_tf_network.png"
)
```

# TFs enriched in branch but not in others
```{python}
branch_tfs = df[df.group=="Branch"]
branch_tfs = branch_tfs[~branch_tfs["name"].isin(persistent_like["name"])]
branch_tfs_up = branch_tfs[branch_tfs.direction=="up"]
branch_tfs_down = branch_tfs[branch_tfs.direction=="down"]
```

```{python}
plt.close("all")
plt.figure(figsize=(24,8))
sc.pl.matrixplot(
    adata=score,
    var_names=branch_tfs.name,
    groupby="lineage_group",
    dendrogram=False,
    standard_scale="var",
    colorbar_title="Z-scaled scores",
    cmap="RdBu_r"
)
plt.savefig("tf_enrichment/branch_only.png", dpi=300)
plt.close()
```

# save various TF lists to put into pathway enrichment analysis
```{python}
persistent_up.to_csv("tf_enrichment/TFs_active_branch_persisting.csv")
branch_tfs_up.to_csv("tf_enrichment/TFs_active_branch.csv")
branch_tfs_down.to_csv("tf_enrichment/TFs_inactive_branch.csv")
```