---
title: "Untitled"
format: html
---


```{python}
import scanpy as sc
import numpy as np
import anndata as ad
import pandas as pd
import os
import seaborn as sns
from seaborn import objects as so
import matplotlib.pyplot as plt
import scvi
import harmonypy as hm
```

```{python}
carpall_one = sc.read("2.carpall_doublets_identified.h5ad")
```

# ensure X layer is set up properly as sce conversion for previous doublet detection can mess with it
```{python}
carpall_one.X = carpall_one.layers["counts"].copy()
```

# identify mito, ribo and hb genes
```{python}
carpall_one.var["mt"] = carpall_one.var_names.str.startswith("MT-")
carpall_one.var["ribo"] = carpall_one.var_names.str.startswith(("RPS", "RPL"))
carpall_one.var["hb"] = carpall_one.var_names.str.contains(r"^HB[ABDEGMQZ]\d*(?!\w)")
```

```{python}
sc.pp.calculate_qc_metrics(
    carpall_one, qc_vars=["mt", "ribo", "hb"], inplace=True, percent_top=[20], log1p=True
)
carpall_one
```

```{python}
order = ["Product", "Early", "Mid", "Late"]
carpall_one.obs["Timepoint_bin"] = pd.Categorical(
    carpall_one.obs["Timepoint_bin"],
    categories=order,
    ordered=True
)
```

```{python}
carpall_one.obs["patient_timepoint"] = (
    carpall_one.obs["Patient"].astype(str)
    + "_"
    + carpall_one.obs["Timepoint_bin"].astype(str)
)
```

```{python}
fig, axes = plt.subplots(
    nrows=5,
    ncols=1
)

vars_ = ["pct_counts_mt", "pct_counts_ribo", "pct_counts_hb", "n_genes_by_counts", "total_counts"]
thresholds = {
    "pct_counts_mt": [20],
    "pct_counts_ribo": [50],
    "pct_counts_hb": [5],
    "n_genes_by_counts": [300,4000],
    "total_counts" : [500,10000]
}

for ax, var in zip(axes, vars_):

    sc.pl.violin(
        carpall_one,
        keys=var,
        groupby="patient_timepoint",
        stripplot=False,
        ax=ax,
        show=False,
        rotation = 45
    )

    if var in thresholds:
        for t in thresholds[var]:
            ax.axhline(
                y=t,
                linestyle="--",
                linewidth=1,
                color="red"
            )

    ax.grid(False)

plt.subplots_adjust(hspace=0.3)

fig.set_size_inches(14, 14)
print(fig.get_size_inches())
fig.savefig("pre_qc_violins.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
cell_counts = (
    carpall_one.obs["Patient"]
    .value_counts()
    .reset_index()
)

cell_counts.columns = ["Patient", "n_cells"]
cell_counts
cell_counts.to_csv("patient_cell_counts_pre_qc.csv")
```

```{python}
ax = cell_counts.plot(kind="bar", figsize=(10, 4))

ax.set_xlabel("Patient")
ax.set_ylabel("Number of cells")
ax.set_title("Cells per Patient")

plt.tight_layout()
plt.show()
```

```{python}
carpall_one = carpall_one[(carpall_one.obs['pct_counts_mt'] < 20) & 
    (carpall_one.obs['pct_counts_ribo'] < 50) &
    (carpall_one.obs['pct_counts_hb'] < 10) &
    (carpall_one.obs['total_counts'] > 500) & 
    (carpall_one.obs['total_counts'] < 10000) & 
    (carpall_one.obs['n_genes_by_counts'] > 300) & 
    (carpall_one.obs['n_genes_by_counts'] < 4000), :].copy()
```

```{python}
cell_counts = (
    carpall_one.obs["Patient"]
    .value_counts()
    .reset_index()
)

cell_counts.columns = ["Patient", "n_cells"]
cell_counts
cell_counts.to_csv("patient_cell_counts_post_qc.csv")
```

```{python}
pre = pd.read_csv("patient_cell_counts_pre_qc.csv")
pre = pre.rename(columns = {"n_cells": "counts_pre"})
post = pd.read_csv("patient_cell_counts_post_qc.csv")
post = post.rename(columns = {"n_cells": "counts_post"})
cell_counts = pd.merge(pre, post, how = "inner", on = "Patient")
cell_counts = cell_counts.drop(columns = "Unnamed: 0_x")
cell_counts = cell_counts.drop(columns = "Unnamed: 0_y")
cell_counts = pd.melt(cell_counts, id_vars=["Patient"], var_name="qc_stage", value_name="n_cells")
```

```{python}
plt.close("all")
plt.clf()

fig, ax = plt.subplots(figsize=(6, 4))

sns.barplot(
    data=cell_counts,
    x="Patient",
    y="n_cells",
    hue="qc_stage",
    ax=ax
)

fig.tight_layout()
fig.savefig("cell_counts_filtering.png", dpi=300, bbox_inches="tight")
plt.show()
```

```{python}
cell_counts = (
    carpall_one.obs[["Patient", "Timepoint_bin"]]
    .value_counts()
    .reset_index(name="n_cells")
)

order = ["Product", "Early", "Mid", "Late"]

plt.close("all")
plt.clf()

fig, ax = plt.subplots(figsize=(6, 4))

sns.barplot(
    data=cell_counts,
    x="Patient",
    y="n_cells",
    hue="Timepoint_bin",
    hue_order=order,
    ax=ax
)

fig.tight_layout()
fig.savefig("cell_counts_patient_time.png", dpi=300, bbox_inches="tight")
plt.show()
```


```{python}
sc.pp.normalize_total(carpall_one, target_sum=1e4)
sc.pp.log1p(carpall_one)
carpall_one.layers['logcounts'] = carpall_one.X.copy()
```

```{python}
carpall_one.obs["cellbender_applied_cat"] = (
    carpall_one.obs["cellbender_applied"]
    .map({True: "Yes", False: "No"})
    .astype("category")
)
```

```{python}
plt.figure()
sns.histplot(
        carpall_one.layers['counts'].sum(1), bins=500, kde=False
    )
plt.show()

plt.figure()
sns.histplot(
        carpall_one.layers['logcounts'].sum(1), bins=500, kde=False
    )
plt.show()
```

```{python}
carpall_one.obs["batch"] = (
    carpall_one.obs["file_id"]
    .str.extract(r"count_(\d+)_CAR")
)
```

# excluding the two samples with fewer than 50 cells (6 and 2 cells respectively)
```{python}
sample_sizes = carpall_one.obs["GEX_id"].value_counts()

sample_sizes[sample_sizes < 50]

keep_samples = sample_sizes[sample_sizes >= 50].index

carpall_one = carpall_one[
    carpall_one.obs["GEX_id"].isin(keep_samples)
].copy()
```

```{python}
sc.pp.highly_variable_genes(
    carpall_one, 
    n_top_genes=2000, 
    flavor="cell_ranger", 
    batch_key='GEX_id', 
    layer = 'logcounts',
    subset = False
)
```

# adding controversial scaling step - also allows latent variables such as percent mito to be regressed out
# in seurat scaling is standard, only in scanpy seems an issue and i lean towards including it
```{python}
carpall_one_hvg = carpall_one[:, carpall_one.var.highly_variable].copy()

sc.pp.regress_out(carpall_one_hvg, ["pct_counts_mt"])
sc.pp.scale(carpall_one_hvg)
sc.pp.pca(carpall_one_hvg)
```

```{python}
carpall_one.obsm["X_pca"] = carpall_one_hvg.obsm["X_pca"]
carpall_one.uns["pca"] = carpall_one_hvg.uns["pca"]
```

```{python}
plt.figure()
sc.pl.pca_variance_ratio(carpall_one, n_pcs=50, log=True)
plt.savefig("Elbow_plot.png", dpi=300)
```

```{python}
sc.pp.neighbors(carpall_one, n_pcs=25, use_rep="X_pca")
sc.tl.umap(carpall_one, random_state=2026)
```

```{python}
fig = sc.pl.umap(carpall_one, color=["batch", "Patient"], 
wspace=0.5,show=False, size = 2, ncols=2,frameon = False, return_fig = True)
fig.set_size_inches(14, 6)
print(fig.get_size_inches())
fig.savefig("umap_uncorrected.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
fig = sc.pl.umap(carpall_one, color=["Patient", "Timepoint_bin", "Sort", "Source", "doublet_class", "cellbender_applied"], 
wspace=0.5,show=False, size = 1, ncols=3,frameon = False, return_fig = True)
fig.set_size_inches(12, 6)
print(fig.get_size_inches())
fig.savefig("umap_meta_uncorrected.png", dpi=300, bbox_inches="tight")
plt.close
```

# trying harmony instead
```{python}
pcs = carpall_one.obsm["X_pca"]
print(pcs.shape)
```

```{python}
batch_patient_structure = pd.crosstab(
    carpall_one.obs["batch"],
    carpall_one.obs["patient_timepoint"]
)
```

```{python}
harmony_out = hm.run_harmony(pcs, carpall_one.obs, "Patient")
```

```{python}
# Store corrected PCs back in the AnnData object
carpall_one.obsm['X_pca_harmony'] = harmony_out.Z_corr
sc.pl.pca_variance_ratio(carpall_one, n_pcs=50, log=True)
```

```{python}
# Use harmonized PCs for downstream analysis
sc.pp.neighbors(carpall_one, use_rep='X_pca_harmony', n_pcs=25)
sc.tl.umap(carpall_one)
```

```{python}
fig = sc.pl.umap(carpall_one, color=["batch", "Patient"], 
wspace=0.5,show=False, size = 2, ncols=2,frameon = False, return_fig = True)
fig.set_size_inches(14, 6)
print(fig.get_size_inches())
fig.savefig("umap_harmony.png", dpi=300, bbox_inches="tight")
plt.close
```


```{python}
fig = sc.pl.umap(carpall_one, color=["Patient", "Timepoint_bin", "Sort", "Source", "doublet_class", "cellbender_applied"], 
wspace=0.5,show=False, size = 1, ncols=3,frameon = False, return_fig = True)
fig.set_size_inches(12, 6)
print(fig.get_size_inches())
fig.savefig("umap_meta.png", dpi=300, bbox_inches="tight")
plt.close
```

# after comparing embeddings, it appears harmony may over-correct due to unbalanced nature of batches/overlap with certain timepoints
# additionally, some interesting outlying cluster sin the uncorrected embeddding which need to be assessed (and possibly removed)
# therefore saved object below will be UNCORRECTED version (re-run uncorrected clustering before saving) and all subsequent analysis performed using uncorrected embedding


```{python}
#carpall_one.write_h5ad("3_carpall_one_clustered.h5ad")
carpall_one = sc.read_h5ad("3_carpall_one_clustered.h5ad")
```

```{python}
pd.crosstab(carpall_one.obs["Sort"], carpall_one.obs["Source"])
```

```{python}
fig=sc.pl.umap(carpall_one, color = ["CAT_scFv", "CD3D", "CD8A", "LYZ", "CD14", "FCGR3A", "MZB1", "MKI67", "NCAM1", "CSF3R", "CD68", "CD74", "CD40LG", "CD79B", "PAX5", "CD34"], layer = "logcounts", legend_fontsize="x-large", size = 1, ncols = 4, frameon = False, cmap = "rocket", return_fig=True)
fig.set_size_inches(12, 8)
fig.savefig("umap_key_markers.png", dpi=300, bbox_inches="tight")
plt.close
```

# checking cell cycle genes
```{python}
s_genes = [
    'MCM5','PCNA','TYMS','FEN1','MCM2','MCM4','RRM1','UNG',
    'GINS2','MCM6','CDCA7','DTL','PRIM1','UHRF1','HELLS',
    'RFC2','RPA2','NASP','RAD51AP1','GMNN','WDR76','SLBP',
    'CCNE2','UBR7','POLD3','MSH2','ATAD2','RAD51','RRM2',
    'CDC45','CDC6','EXO1','TIPIN','DSCC1','BLM','CASP8AP2',
    'USP1','CLSPN','POLA1','CHAF1B','BRIP1','E2F8'
]

g2m_genes = [
    'HMGB2','CDK1','NUSAP1','UBE2C','BIRC5','TPX2','TOP2A',
    'NDC80','CKS2','NUF2','CKS1B','MKI67','TMPO','CENPF',
    'TACC3','FAM64A','SMC4','CCNB2','CKAP2L','CKAP2',
    'AURKB','BUB1','KIF11','ANP32E','TUBB4B','GTSE1',
    'KIF20B','HJURP','CDC20','TTK','CDC25C','KIF2C',
    'RANGAP1','NCAPD2','DLGAP5','CDCA3','HMMR','AURKA',
    'PSRC1','ANLN','LBR','CKAP5','CENPE','CTCF','NEK2',
    'G2E3','GAS2L3','CBX5','CENPA'
]

s_present = [g for g in s_genes if g in carpall_one.var_names]
g2m_present = [g for g in g2m_genes if g in carpall_one.var_names]

print(len(s_present), len(g2m_present))
```

```{python}
sc.tl.score_genes_cell_cycle(
    carpall_one,
    s_genes=s_present,
    g2m_genes=g2m_present
)
```

```{python}
fig=sc.pl.umap(
    carpall_one,
    color=["S_score", "G2M_score", "phase"],size=1,ncols =1, frameon=False,
    return_fig=True, cmap="rocket")

fig.set_size_inches(6, 10)
fig.savefig("umap_cell_cycle.png", dpi=300, bbox_inches="tight")
plt.close
```

### checking stress genes
```{python}
stress_genes = ["HSPA1A", "HSPA1B", "HSPB1"]

present = [g for g in stress_genes if g in carpall_one.var_names]
fig=sc.pl.umap(
    carpall_one,
    color=present,size=1,ncols =1, frameon=False,
    return_fig=True, cmap="rocket")

fig.set_size_inches(6, 10)
fig.savefig("umap_stress_genes.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
apoptosis_genes = [
    "CASP3", "CASP6", "CASP7"]

present = [g for g in apoptosis_genes if g in carpall_one.var_names]

fig=sc.pl.umap(
    carpall_one,
    color=present,size=1,ncols =1, frameon=False,
    return_fig=True, cmap="rocket")

fig.set_size_inches(6, 10)
fig.savefig("umap_apoptosis_genes.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
fig=sc.pl.umap(
    carpall_one,
    color=["pct_counts_mt", "pct_counts_hb", "total_counts", "n_genes_by_counts"], 
    size = 1, legend_fontsize="x-large", ncols=2, cmap = "rocket",frameon=False, return_fig=True
)
fig.set_size_inches(8, 6)
fig.savefig("umap_qc_metrics.png", dpi=300, bbox_inches="tight")
plt.close
```


```{python}
fig=sc.pl.umap(carpall_one, color = ["CAT_scFv", "CD3D", "CD8A", "CD8B", "CD4", "TRGV1", "CCR7", "SELL", "IL7R", "TCF7", "GZMB", "GZMK", "FOXP3", "TIGIT", "CD27", "CD28"], legend_fontsize="x-large", size = 1, ncols = 4, frameon = False, cmap = "rocket", return_fig=True)
fig.set_size_inches(10, 8)
fig.savefig("umap_Tcell_markers.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
sc.pl.dotplot(carpall_one, var_names=["CD3D", "LYZ", "CD3D"], groupby="patient_timepoint")
```

```{python}
for res in [0.5,0.6,0.7,0.8,0.9,1,1.5,2]:
    sc.tl.leiden(carpall_one, key_added = "leiden_res_" + str(res), resolution = res, 
    flavor = "igraph", n_iterations = 2, directed = False)
```

```{python}
fig=sc.pl.umap(
    carpall_one,
    color=["leiden_res_0.5",
     "leiden_res_1", "leiden_res_1.5"], 
    size = 1, legend_fontsize="x-large", ncols=3, wspace=0.1, legend_loc="on data",frameon=False, return_fig=True
)
fig.set_size_inches(24, 6)
print(fig.get_size_inches())
fig.savefig("umap_clustering_resolutions.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
sc.pl.dotplot(carpall_one, groupby="leiden_res_0.5", var_names=["CD3D", "CD3E", "CD8A", "CD8B", "CD4", "CD40LG", "SELL", "CCR7", "IL7R", "GZMA", "GZMB", "GZMK", "TIGIT", "FOXP3", "NCAM1", "LYZ", "CD14", "CD68", "CD79A", "MZB1", "PAX5", "CD34"])
```

```{python}
sc.tl.rank_genes_groups(
    carpall_one, groupby="leiden_res_1", method="wilcoxon", key_added="dea_leiden_res_1"
)

sc.tl.filter_rank_genes_groups(
    carpall_one,
    min_in_group_fraction=0.25,
    max_out_group_fraction=0.25,
    key="dea_leiden_res_1",
    key_added="dea_leiden_res_1_filtered",
)
```

```{python}
degs = sc.get.rank_genes_groups_df(
    carpall_one,
    group=None,
    key="dea_leiden_res_1_filtered"
)

degs.to_csv("resolution_1_degs.csv", index=False)
```

```{python}
sc.tl.dendrogram(
    carpall_one,
    groupby="leiden_res_1",
)

sc.pl.rank_genes_groups_dotplot(
    carpall_one, groupby="leiden_res_1", standard_scale="var", n_genes=5, key="dea_leiden_res_1_filtered"
)
```

```{python}
dp=sc.pl.rank_genes_groups_dotplot(
    carpall_one, groupby="leiden_res_1", standard_scale="var", n_genes=10, key="dea_leiden_res_1_filtered", groups = ["7", "9", "11", "19"], return_fig=True
)
dp.make_figure()
fig=dp.fig
fig.set_size_inches(12, 12)
print(fig.get_size_inches())
fig.savefig("resolution_1_specific_cluster_degs_dotplot.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
dp=sc.pl.dotplot(carpall_one, groupby="leiden_res_1", var_names=["CAT_scFv","CD3D", "CD3E", "CD8A", "CD4", "CCR7", "IL7R", "GZMB", "GZMK", "GZMK", "PRF1", "TIGIT", "KLRC2", "NCAM1", "KLRB1", "SLC4A10", "LYZ", "S100A8", "CD14", "FCGR3A", "CD68", "CD79A", "CD79B", "PRDM1", "CD19", "MS4A1", "IGKC", "IGHM", "MZB1", "TCF4", "MKI67"], dendrogram=True,
standard_scale="var", return_fig=True, cmap = "mako_r")
dp.make_figure()
fig=dp.fig
fig.set_size_inches(12, 12)
print(fig.get_size_inches())
fig.savefig("resolution_1_key_genes_dotplot.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
cluster_counts = (
    carpall_one.obs["leiden_res_1"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .reset_index()
)

cluster_counts.columns = ["cluster", "percent_cells"]
```

```{python}
plt.figure()
sns.barplot(data=cluster_counts, x="cluster", y = "percent_cells")

```

# celltypist to assist in annotation

```{python}
import celltypist
from celltypist import models
```

```{python}
models.download_models(
    force_update=True, 
    model=["Immune_All_High.pkl"]
)
model_immune_high = models.Model.load(model="Immune_All_High.pkl")

models.download_models(
    force_update=True, 
    model=["Immune_All_Low.pkl"]
)
model_immune_low = models.Model.load(model="Immune_All_Low.pkl")

models.download_models(
    force_update=True, 
    model=["COVID19_HumanChallenge_Blood.pkl"]
)
model_covid = models.Model.load(model="COVID19_HumanChallenge_Blood.pkl")
```

```{python}
pred_high = celltypist.annotate(
    carpall_one,
    model="Immune_All_High.pkl"
)

ad_high = pred_high.to_adata(insert_conf=True)

carpall_one.obs["celltypist_high_label"] = ad_high.obs["predicted_labels"]
carpall_one.obs["celltypist_high_score"] = ad_high.obs["conf_score"]

pred_low = celltypist.annotate(
    carpall_one,
    model="Immune_All_Low.pkl"
)

ad_low = pred_low.to_adata(insert_conf=True)

carpall_one.obs["celltypist_low_label"] = ad_low.obs["predicted_labels"]
carpall_one.obs["celltypist_low_score"] = ad_low.obs["conf_score"]
```

```{python}
fig = sc.pl.umap(carpall_one, color=["celltypist_high_label", "celltypist_low_label"], 
wspace=1,show=False, size = 1, ncols=2,frameon = False, return_fig = True)
fig.set_size_inches(20, 10)
print(fig.get_size_inches())
fig.savefig("umap_celltypist.png", dpi=300, bbox_inches="tight")
plt.close
```

# remove contaminating clusters and re-run clustering
# will also check cells called as doublets to see if justified removing

```{python}
vars_ = ["pct_counts_mt", "n_genes_by_counts", "total_counts"]
plt.figure(figsize=(10,6))
sc.pl.violin(carpall_one, keys=vars_, groupby="doublet_class", stripplot=False, show=True)
plt.savefig("violin_qc_doublets.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
for k in [
    "dea_leiden_res_1",
    "dea_leiden_res_1_filtered",
    "dendrogram_leiden_res_1"
]:
    carpall_one.uns.pop(k, None)
#carpall_one.write_h5ad("4_carpall_clustering_round1.h5ad")
carpall_one = sc.read_h5ad("4_carpall_clustering_round1.h5ad")
```

```{python}
to_remove = ["7","9","34"]
cells_before = carpall_one.n_obs
carpall_one = carpall_one[
    ~(carpall_one.obs["leiden_res_1"].isin(to_remove)) &
    (carpall_one.obs["doublet_class"] == "singlet")].copy()
cells_after = carpall_one.n_obs
sc.pl.umap(carpall_one, color = "leiden_res_1", legend_loc = "on data")
```

```{python}
sample_sizes = carpall_one.obs["GEX_id"].value_counts()

sample_sizes[sample_sizes < 50]

keep_samples = sample_sizes[sample_sizes >= 50].index
```

```{python}
carpall_one = carpall_one[
    carpall_one.obs["GEX_id"].isin(keep_samples)
].copy()
```

```{python}
sc.pp.highly_variable_genes(
    carpall_one, 
    n_top_genes=2000, 
    flavor="cell_ranger", 
    batch_key='GEX_id', 
    layer = 'logcounts',
    subset = False
)
```

```{python}
carpall_one_hvg = carpall_one[:, carpall_one.var.highly_variable].copy()

sc.pp.regress_out(carpall_one_hvg, ["pct_counts_mt"])
sc.pp.scale(carpall_one_hvg)
sc.pp.pca(carpall_one_hvg)
```

```{python}
carpall_one.obsm["X_pca"] = carpall_one_hvg.obsm["X_pca"]
carpall_one.uns["pca"] = carpall_one_hvg.uns["pca"]
```

```{python}
plt.figure()
sc.pl.pca_variance_ratio(carpall_one, n_pcs=50, log=True)
plt.savefig("Elbow_plot.png", dpi=300)
```

```{python}
sc.pp.neighbors(carpall_one, n_pcs=25, use_rep="X_pca")
sc.tl.umap(carpall_one, random_state=2026)
```

```{python}
fig = sc.pl.umap(carpall_one, color=["batch", "Patient"], 
wspace=0.5,show=False, size = 2, ncols=2,frameon = False, return_fig = True)
fig.set_size_inches(14, 6)
print(fig.get_size_inches())
fig.savefig("umap_2nd_round.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
fig = sc.pl.umap(carpall_one, color=["Patient", "Timepoint_bin", "Sort", "Source"], 
wspace=0.5,show=False, size = 1, ncols=2,frameon = False, return_fig = True)
fig.set_size_inches(12, 6)
print(fig.get_size_inches())
fig.savefig("umap_2nd_round_meta.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
fig=sc.pl.umap(carpall_one, color = ["CAT_scFv", "CD3D", "CD8A", "CD4", "LYZ", "CD14", "FCGR3A", "CD68", "NCAM1", "GZMB", "GZMK", "CSF3R", "TCF4", "MZB1", "IGHM", "MKI67"], layer = "logcounts", legend_fontsize="x-large", size = 1, ncols = 4, frameon = False, cmap = "rocket", return_fig=True)
fig.set_size_inches(12, 8)
fig.savefig("umap_2nd_key_markers.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
for res in [0.5,0.6,0.7,0.8,0.9,1,1.5,2]:
    sc.tl.leiden(carpall_one, key_added = "leiden_res_" + str(res), resolution = res, 
    flavor = "igraph", n_iterations = 2, directed = False)
```

```{python}
fig=sc.pl.umap(
    carpall_one,
    color=["leiden_res_0.5",
     "leiden_res_1", "leiden_res_1.5"], 
    size = 1, legend_fontsize="x-large", ncols=3, wspace=0.1, legend_loc="on data",frameon=False, return_fig=True
)
fig.set_size_inches(24, 6)
print(fig.get_size_inches())
fig.savefig("umap_2nd_clustering_resolutions.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
sc.tl.dendrogram(carpall_one, groupby = "leiden_res_0.5")
sc.pl.dendrogram(carpall_one, groupby = "leiden_res_0.5")

sc.tl.dendrogram(carpall_one, groupby = "leiden_res_1")
sc.pl.dendrogram(carpall_one, groupby = "leiden_res_1")
```

```{python}
pred_high = celltypist.annotate(
    carpall_one,
    model="Immune_All_High.pkl"
)

ad_high = pred_high.to_adata(insert_conf=True)

carpall_one.obs["celltypist_high_label"] = ad_high.obs["predicted_labels"]
carpall_one.obs["celltypist_high_score"] = ad_high.obs["conf_score"]

pred_low = celltypist.annotate(
    carpall_one,
    model="Immune_All_Low.pkl"
)

ad_low = pred_low.to_adata(insert_conf=True)

carpall_one.obs["celltypist_low_label"] = ad_low.obs["predicted_labels"]
carpall_one.obs["celltypist_low_score"] = ad_low.obs["conf_score"]

pred_covid = celltypist.annotate(
    carpall_one,
    model="COVID19_HumanChallenge_Blood.pkl"
)

ad_covid = pred_covid.to_adata(insert_conf=True)

carpall_one.obs["celltypist_covid_label"] = ad_covid.obs["predicted_labels"]
carpall_one.obs["celltypist_covid_score"] = ad_covid.obs["conf_score"]
```

```{python}
fig = sc.pl.umap(carpall_one, color=["celltypist_high_label", "celltypist_low_label", "celltypist_covid_label"], 
wspace=1,show=False, size = 1, ncols=3,frameon = False, return_fig = True)
fig.set_size_inches(25, 10)
print(fig.get_size_inches())
fig.savefig("umap_2nd_celltypist.png", dpi=300, bbox_inches="tight")
plt.close
```

# getting celltype proportions
```{python}
label_props = carpall_one.obs["celltypist_high_label"].value_counts(normalize=True)

major_labels = label_props[label_props >= 0.05].index

labels = carpall_one.obs["celltypist_high_label"].astype(str)

carpall_one.obs["celltypist_high_label_5pct"] = labels.where(
    labels.isin(major_labels),
    "Other"
)
```

```{python}
label_props = carpall_one.obs["celltypist_low_label"].value_counts(normalize=True)

major_labels = label_props[label_props >= 0.01].index

labels = carpall_one.obs["celltypist_low_label"].astype(str)

carpall_one.obs["celltypist_low_label_1pct"] = labels.where(
    labels.isin(major_labels),
    "Other"
)
```

```{python}
label_props = carpall_one.obs["celltypist_covid_label"].value_counts(normalize=True)

major_labels = label_props[label_props >= 0.01].index

labels = carpall_one.obs["celltypist_covid_label"].astype(str)

carpall_one.obs["celltypist_covid_label_1pct"] = labels.where(
    labels.isin(major_labels),
    "Other"
)
```

```{python}
custom_palette = {
    "Tcm/Naive cytotoxic T cells" : "lime",
    "Tem/Trm cytotoxic T cells" : "palegreen",
    "Tem/Temra cytotoxic T cells" : "seagreen",
    "Tcm/Naive helper T cells" : "royalblue",
    "Tem/Effector helper T cells" : "deepskyblue",
    "Regulatory T cells" : "darkturquoise",
    "CD16+ NK cells" : "mediumorchid",
    "NK cells" : "magenta",
    "Classical monocytes" : "red",
    "Non-classical monocytes" : "darkred",
    "Memory B cells" : "gold",
    "Other" : "grey"
}


fig = sc.pl.umap(carpall_one, color=["celltypist_low_label_1pct", "celltypist_low_score"], 
wspace=1,show=False, size = 1, ncols=2,frameon = False, return_fig = True, palette=custom_palette)
fig.set_size_inches(12, 5)
print(fig.get_size_inches())
fig.savefig("umap_celltypist_low_1pct.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
covid_palette = {
    "Monocyte CD14+":"gold",
    "Monocyte CD16+":"olive",
    "NK":"mediumpurple",
    "T CD4 Helper 0":"deepskyblue",
    "T CD4 Naive":"blue",
    "T CD8 CM":"lightcoral",
    "T CD8 CTL":"hotpink",
    "T CD8 EM":"darkred",
    "T CD8 EMRA":"orangered",
    "T CD8 Naive":"mediumvioletred",
    "T Double Negative":"lime",
    "T G/D CM":"green",
    "T G/D non-Dv2/Gv9":"palegreen",
    "Other" : "grey"
}

fig = sc.pl.umap(carpall_one, color=["celltypist_covid_label_1pct", "celltypist_covid_score"], 
wspace=1,show=False, size = 1, ncols=2,frameon = False, return_fig = True,palette=covid_palette)
fig.set_size_inches(12, 5)
print(fig.get_size_inches())
fig.savefig("umap_celltypist_covid_1pct.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
counts = pd.crosstab(
    carpall_one.obs["Timepoint_bin"],
    carpall_one.obs["celltypist_low_label_1pct"]
)
props = counts.div(counts.sum(axis=1), axis=0)
props= props * 100
props.head()
```

```{python}
props = props.reset_index()
props = props.melt(id_vars = "Timepoint_bin", var_name = "celltype", value_name = "percent")
```

```{python}
p = (
    so.Plot(props, x="Timepoint_bin", y="percent", color="celltype")
    .scale(color=custom_palette)
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(10,6))
)

p.save("celltypist_proportions_time.png", dpi=300, bbox_inches="tight")
```

# split proportion changes by blood or bone marrow origin
```{python}
counts = pd.crosstab(
    index=[carpall_one.obs["Timepoint_bin"], carpall_one.obs["Source"]],
    columns=carpall_one.obs["celltypist_low_label_1pct"]
)

props = counts.div(counts.sum(axis=1), axis=0) * 100

props = (
    props
    .reset_index()
    .melt(
        id_vars=["Timepoint_bin", "Source"],
        var_name="celltype",
        value_name="percent"
    )
)
```

```{python}
p = (
    so.Plot(props, x="Timepoint_bin", y="percent", color="celltype")
    .facet("Source")
    .scale(color=custom_palette)
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(10,6))
)

p.save("celltypist_proportions_time_and_source.png", dpi=300, bbox_inches="tight")
```

# celltypist proportions per leiden cluster
```{python}
counts = pd.crosstab(
    index=[carpall_one.obs["leiden_res_1"]],
    columns=carpall_one.obs["celltypist_low_label_1pct"]
)

props = counts.div(counts.sum(axis=1), axis=0) * 100

props = (
    props
    .reset_index()
    .melt(
        id_vars=["leiden_res_1"],
        var_name="celltype",
        value_name="percent"
    )
)
```

```{python}
p = (
    so.Plot(props, x="leiden_res_1", y="percent", color="celltype")
    .scale(color=custom_palette)
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(10,6))
)

p.save("celltypist_proportions_leiden_res_1.png", dpi=300, bbox_inches="tight")
```

```{python}
counts = pd.crosstab(
    index=[carpall_one.obs["leiden_res_1"]],
    columns=carpall_one.obs["celltypist_covid_label_1pct"]
)

props = counts.div(counts.sum(axis=1), axis=0) * 100

props = (
    props
    .reset_index()
    .melt(
        id_vars=["leiden_res_1"],
        var_name="celltype",
        value_name="percent"
    )
)
```

```{python}
p = (
    so.Plot(props, x="leiden_res_1", y="percent", color="celltype")
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(10,6))
)

p.save("covid_celltypist_proportions_leiden_res_1.png", dpi=300, bbox_inches="tight")
```

# proportion of car+ cells in each cluster
```{python}
counts = pd.crosstab(
    index=[carpall_one.obs["leiden_res_1"]],
    columns=carpall_one.obs["Sort"]
)

props = counts.div(counts.sum(axis=1), axis=0) * 100

props = (
    props
    .reset_index()
    .melt(
        id_vars=["leiden_res_1"],
        var_name="sort",
        value_name="percent"
    )
)
```

```{python}
p = (
    so.Plot(props, x="leiden_res_1", y="percent", color="sort")
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(10,6))
)

p.save("sorted_proportions_leiden_res_1.png", dpi=300, bbox_inches="tight")
```

# of the clusters that look strange (mixed celltypist or high proportion of "other"), they are likely the returning cancer cells, so will look at their full celltypist annotation to see what else it thinks are there

```{python}
counts = pd.crosstab(
    index=[carpall_one.obs["leiden_res_1"]],
    columns=carpall_one.obs["celltypist_low_label"]
)

props = counts.div(counts.sum(axis=1), axis=0) * 100

props = (
    props
    .reset_index()
    .melt(
        id_vars=["leiden_res_1"],
        var_name="celltype",
        value_name="percent"
    )
)
keep = ["3", "4", "30", "31"]
props = props[props["leiden_res_1"].isin(keep)]
```

```{python}
p = (
    so.Plot(props, x="leiden_res_1", y="percent", color="celltype")
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(10,6))
)

p.save("celltypist_proportions_potential_cancer_clusters.png", dpi=300, bbox_inches="tight")
```

# DEA of leiden clusters
```{python}
sc.tl.rank_genes_groups(
    carpall_one, groupby="leiden_res_1", method="wilcoxon", key_added="dea_leiden_res_1"
)

sc.tl.filter_rank_genes_groups(
    carpall_one,
    min_in_group_fraction=0.25,
    max_out_group_fraction=0.25,
    key="dea_leiden_res_1",
    key_added="dea_leiden_res_1_filtered",
)
```

```{python}
degs = sc.get.rank_genes_groups_df(
    carpall_one,
    group=None,
    key="dea_leiden_res_1_filtered"
)

degs.to_csv("resolution_1_degs.csv", index=False)
```

```{python}
sc.tl.dendrogram(
    carpall_one,
    groupby="leiden_res_1",
)

sc.pl.rank_genes_groups_dotplot(
    carpall_one, groupby="leiden_res_1", standard_scale="var", n_genes=5, key="dea_leiden_res_1_filtered", cmap="mako"
)
plt.close
```

```{python}
axes = sc.pl.correlation_matrix(
    carpall_one,
    groupby="leiden_res_1",
    show=False
)

fig = axes[0].figure
fig.set_size_inches(6, 6)

print(fig.get_size_inches())

fig.savefig(
    "leiden_res_1_correlation_matrix.png",
    dpi=300,
    bbox_inches="tight"
)
```

```{python}
sc.pl.umap(carpall_one, color="leiden_res_1")
```

```{python}
dp=sc.pl.dotplot(carpall_one, groupby="leiden_res_1", var_names=["CAT_scFv","CD3D", "CD3E", "CD8A", "CD4", "CCR7", "IL7R", "CD40LG", "GZMB", "GZMK", "GZMK", "PRF1", "TIGIT", "KLRC2", "NCAM1", "KLRB1", "SLC4A10", "LYZ", "S100A8", "CD14", "FCGR3A", "CLEC4C", "IL3RA", "CD68", "CD79A", "CD79B", "CSF3R","DNTT", "VPREB1", "IGHM", "MZB1", "TCF4", "MKI67", "TRDV2", "TRGV9", "TRDC"], dendrogram=True,
standard_scale="var", return_fig=True, cmap = "mako_r")
dp.make_figure()
fig=dp.fig
fig.set_size_inches(12, 12)
print(fig.get_size_inches())
fig.savefig("resolution_1_key_genes_dotplot.png", dpi=300, bbox_inches="tight")
plt.close
```

# broad annotation
```{python}
labels = {
    "0":"Myeloid",
    "1":"Myeloid",
    "2":"Myeloid",
    "3":"B-ALL relapse",
    "4":"B-ALL relapse",
    "5":"CD8+ T",
    "6":"Cycling DN CAR T",
    "7":"CD8+ T",
    "8":"CD16lo NK",
    "9":"CD8+ T",
    "10":"CD8+ CAR T",
    "11":"CD8+ CAR T",
    "12":"CD8+ CAR T",
    "13":"CD4+ T",
    "14":"Mixed T",
    "15":"CD4+ T",
    "16":"CD8+ CAR T",
    "17":"Naive Mixed T",
    "18":"VD2- GD T",
    "19":"CD8+ CAR T",
    "20":"DN CAR T",
    "21":"Mixed CAR T",
    "22":"Mixed T",
    "23":"CD8+ CAR T",
    "24":"CD8+ T",
    "25":"VD2+ GD T",
    "26":"DN CAR T",
    "27":"CD16+ NK",
    "28":"Mixed T",
    "29":"VD2- GD T",
    "30":"B-ALL relapse",
    "31":"CD8+ CAR T",
    "32":"CD8+ T"

}

carpall_one.obs["broad_labels"] = (
    carpall_one.obs["leiden_res_1"]
    .map(labels)
    .astype("category")
)
sc.tl.dendrogram(carpall_one, groupby="broad_labels")
```

```{python}
custom_palette = {
    "Tcm/Naive cytotoxic T cells" : "lime",
    "Tem/Trm cytotoxic T cells" : "palegreen",
    "Tem/Temra cytotoxic T cells" : "seagreen",
    "Tcm/Naive helper T cells" : "royalblue",
    "Tem/Effector helper T cells" : "deepskyblue",
    "Regulatory T cells" : "darkturquoise",
    "CD16+ NK cells" : "mediumorchid",
    "NK cells" : "magenta",
    "Classical monocytes" : "red",
    "Non-classical monocytes" : "darkred",
    "Memory B cells" : "gold",
    "Other" : "grey"
}


fig = sc.pl.umap(carpall_one, color=["celltypist_low_label_1pct", "celltypist_low_score"], 
wspace=1,show=False, size = 1, ncols=2,frameon = False, return_fig = True, palette=custom_palette)
fig.set_size_inches(12, 5)
print(fig.get_size_inches())
fig.savefig("umap_celltypist_low_1pct.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
label_palette = {
    "Myeloid":"gold",
    "CD8+ CAR T":"darkred",
    "Cycling DN CAR T":"darkseagreen",
    "CD8+ T":"red",
    "CD4+ T":"blue",
    "Mixed CAR T":"teal",
    "Mixed T":"skyblue",
    "DN CAR T":"springgreen",
    "VD2- GD T":"green",
    "VD2+ GD T":"greenyellow",
    "Naive Mixed T":"lightcoral",
    "CD16+ NK":"darkorchid",
    "CD16lo NK":"mediumpurple",
    "B-ALL relapse":"grey"
}

fig = sc.pl.umap(carpall_one, color=["broad_labels"], 
wspace=1,show=False, size = 2, ncols=1,frameon = False, return_fig = True,palette=label_palette)
fig.set_size_inches(6, 4)
print(fig.get_size_inches())
fig.savefig("umap_broad_annotation.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
fig=sc.pl.umap(carpall_one, color = ["CAT_scFv", "CD3D", "CD8A", "CD4", "LYZ", "NCAM1"], legend_fontsize="x-large", size = 1, ncols = 3, frameon = False, cmap = "rocket", return_fig=True)
fig.set_size_inches(6, 3)
fig.savefig("umap_cd4_cd8.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
dp=sc.pl.dotplot(carpall_one, groupby="broad_labels", var_names=["CAT_scFv","CD3D", "CD8A", "CD4", "CCR7", "IL7R", "CD40LG", "GZMB", "GZMK", "PRF1", "NCAM1", "TRDV2", "TRGV9", "TRDC", "LYZ", "CD14", "FCGR3A", "IGHM", "CD34", "MZB1", "TCF4", "MKI67"], dendrogram=True,
standard_scale="var", return_fig=True, cmap = "mako_r")
dp.make_figure()
fig=dp.fig
fig.set_size_inches(8, 6)
print(fig.get_size_inches())
fig.savefig("broad_labels_key_genes_dotplot.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
counts = pd.crosstab(
    carpall_one.obs["Timepoint_bin"],
    carpall_one.obs["broad_labels"]
)
props = counts.div(counts.sum(axis=1), axis=0)
props= props * 100
props.head()
```

```{python}
props = props.reset_index()
props = props.melt(id_vars = "Timepoint_bin", var_name = "celltype", value_name = "percent")
```

```{python}
p = (
    so.Plot(props, x="Timepoint_bin", y="percent", color="celltype")
    .scale(color=label_palette)
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(8,4))
)

p.save("broad_labels_proportions_time.png", dpi=300, bbox_inches="tight")
```

```{python}
counts = pd.crosstab(
    carpall_one.obs["Patient"],
    carpall_one.obs["broad_labels"]
)
props = counts.div(counts.sum(axis=1), axis=0)
props= props * 100
props.head()
```

```{python}
props = props.reset_index()
props = props.melt(id_vars = "Patient", var_name = "celltype", value_name = "percent")
```

```{python}
p = (
    so.Plot(props, x="Patient", y="percent", color="celltype")
    .scale(color=label_palette)
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(7,3))
)

p.save("broad_labels_proportions_patient.png", dpi=300, bbox_inches="tight")
```

```{python}
sort_map = {
    "CD3+CAT+": "CAR+",
    "CD3+CAT-": "CAR-",
    "CD3-CAT-": "CAR-",
    "NoSo": "CAR-",
}

carpall_one.obs["Sort_clean"] = (
    carpall_one.obs["Sort"]
    .map(sort_map)
    .astype("category")
)
```

```{python}
counts = pd.crosstab(
    [carpall_one.obs["Timepoint_bin"], carpall_one.obs["Sort_clean"]],
    carpall_one.obs["broad_labels"]
)
props = counts.div(counts.sum(axis=1), axis=0)
props= props * 100
props.head()
```

```{python}
props = props.reset_index()
props = props.melt(id_vars = ["Timepoint_bin", "Sort_clean"], var_name = "celltype", value_name = "percent")
```

```{python}
p = (
    so.Plot(props, x="Timepoint_bin", y="percent", color="celltype")
    .facet(col="Sort_clean")
    .scale(color=label_palette)
    .add(so.Bar(), so.Stack())
    .theme({
        "axes.facecolor": "w", 
        "axes.edgecolor": "grey"})
    .layout(size=(10,6))
)

p.save("labels_sort_proportions_time.png", dpi=300, bbox_inches="tight")
```

```{python}
fig = sc.pl.umap(carpall_one, color=["Sort_clean"], 
wspace=1,show=False, size = 1, ncols=2,frameon = False, return_fig = True)
fig.set_size_inches(12, 5)
print(fig.get_size_inches())
fig.savefig("umap_sort_clean.png", dpi=300, bbox_inches="tight")
plt.close
```

```{python}
axes = sc.pl.correlation_matrix(
    carpall_one,
    groupby="broad_labels",
    show=False
)

fig = axes[0].figure
fig.set_size_inches(6, 6)

print(fig.get_size_inches())

fig.savefig(
    "broad_labels_correlation_matrix.png",
    dpi=300,
    bbox_inches="tight"
)
```

```{python}
sc.tl.embedding_density(carpall_one, basis="umap", groupby="Timepoint_bin")

fig=sc.pl.embedding_density(carpall_one, basis="umap", key="umap_density_Timepoint_bin", group=["Early", "Mid", "Late"], return_fig=True)
fig.set_size_inches(15, 5)
print(fig.get_size_inches())
fig.savefig("umap_time_density.png", dpi=300, bbox_inches="tight")
plt.close
```


```{python}
for k in [
    "dea_leiden_res_1",
    "dea_leiden_res_1_filtered",
    "dendrogram_leiden_res_1"
]:
    carpall_one.uns.pop(k, None)
#carpall_one.write_h5ad("5_carpall_annotated.h5ad")
carpall_one = sc.read_h5ad("5_carpall_annotated.h5ad")
```

# subset out CAR+ cells for separate analysis
```{python}
cars = carpall_one[carpall_one.obs["Sort_clean"] == "CAR+"].copy()
cars.write_h5ad("1_cars_only.h5ad")
```